export const themeData = JSON.parse("{\"encrypt\":{\"config\":{\"/demo/encrypt.html\":[\"$2a$10$hVcy32xSsZ2.EX2Dpi5kMOAdpF7Rx5v5t.vpZOVSkbf/Lk.KsAyJi\"]}},\"author\":{\"name\":\"暮里文集\",\"url\":\"http://eb118-file.cdn.bcebos.com/upload/301083B150A1C45C8484410BCAC43F09?x-bce-process=style/wm_ai\"},\"logo\":\"logo.svg\",\"repo\":\"RiKa0-0/vuepress-blog\",\"docsDir\":\"src\",\"blog\":{\"medias\":{\"稀土掘金\":\"https://juejin.cn/user/160992116607870\",\"BiliBili\":\"https://space.bilibili.com/431556388\",\"Email\":\"muri0_0@qq.com\",\"Gitee\":\"https://gitee.com/rika00\",\"GitHub\":\"https://github.com/RiKa0-0\",\"Zhihu\":\"https://www.zhihu.com/people/shi-san-xie-a-89\"}},\"locales\":{\"/\":{\"lang\":\"en-US\",\"navbarLocales\":{\"langName\":\"English\",\"selectLangAriaLabel\":\"Select language\"},\"metaLocales\":{\"author\":\"Author\",\"date\":\"Writing Date\",\"origin\":\"Original\",\"views\":\"Page views\",\"category\":\"Category\",\"tag\":\"Tag\",\"readingTime\":\"Reading Time\",\"words\":\"Words\",\"toc\":\"On This Page\",\"prev\":\"Prev\",\"next\":\"Next\",\"lastUpdated\":\"Last update\",\"contributors\":\"Contributors\",\"editLink\":\"在 GitHub 上编辑此页\",\"print\":\"Print\"},\"blogLocales\":{\"article\":\"Articles\",\"articleList\":\"Article List\",\"category\":\"Category\",\"tag\":\"Tag\",\"timeline\":\"Timeline\",\"timelineTitle\":\"Yesterday Once More!\",\"all\":\"All\",\"intro\":\"Personal Intro\",\"star\":\"Star\"},\"paginationLocales\":{\"prev\":\"Prev\",\"next\":\"Next\",\"navigate\":\"Jump to\",\"action\":\"Go\",\"errorText\":\"Please enter a number between 1 and $page !\"},\"outlookLocales\":{\"themeColor\":\"Theme Color\",\"darkmode\":\"Theme Mode\",\"fullscreen\":\"Full Screen\"},\"encryptLocales\":{\"iconLabel\":\"Page Encrypted\",\"placeholder\":\"Enter password\",\"remember\":\"Remember password\",\"errorHint\":\"Please enter the correct password!\"},\"routeLocales\":{\"skipToContent\":\"Skip to main content\",\"notFoundTitle\":\"Page not found\",\"notFoundMsg\":[\"There’s nothing here.\",\"How did we get here?\",\"That’s a Four-Oh-Four.\",\"Looks like we've got some broken links.\"],\"back\":\"Go back\",\"home\":\"Take me home\",\"openInNewWindow\":\"Open in new window\"},\"navbar\":[\"/\",{\"text\":\"大数据\",\"icon\":\"book\",\"link\":\"#\"},{\"text\":\"人工智能\",\"icon\":\"book\",\"link\":\"#\"},{\"text\":\"工程架构\",\"icon\":\"book\",\"link\":\"#\"},{\"text\":\"随笔\",\"icon\":\"book\",\"link\":\"#\"},{\"text\":\"小说\",\"icon\":\"book\",\"link\":\"#\"}],\"sidebar\":{\"/\":[\"\",\"intro\"]},\"footer\":\"到底了哟~\",\"displayFooter\":true,\"blog\":{\"description\":\"工程、大数据全栈架构师\",\"intro\":\"/intro.html\"}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
